const REAL_TIME_SERVER_HOST = 'http://localhost';
const REAL_TIME_SERVER_PORT = 8080;

const AUTH_SERVER_URL_HOST = 'http://localhost';
const AUTH_SERVER_URL_PORT = 8080;

const APP_NAME = 'ASAAT';

export const AppConfig = {
    REAL_TIME_SERVER_URL: `${REAL_TIME_SERVER_HOST}:${REAL_TIME_SERVER_PORT}/`,
    API_SERVER_URL: `${REAL_TIME_SERVER_HOST}:${REAL_TIME_SERVER_PORT}/`,
    AUTH_SERVER_URL: `${AUTH_SERVER_URL_HOST}:${AUTH_SERVER_URL_PORT}`,
    APP_NAME: APP_NAME
};
